from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from src.ingestion.domain.entities import CodeEntity


class AgentState(BaseModel):
    """
    This state object is passed between agents in the orchestration flow,
    accumulating information at each step:

    1. PLANNING: Planner analyzes user goal and generates search query
    2. RETRIEVAL: RAG system retrieves relevant code entities
    3. CODING: Coder generates fix based on context
    4. REVIEWING: Reviewer validates the proposed fix
    5. APPROVED/REJECTED: Final state with decision

    The state supports a retry loop where a rejected fix returns to CODING
    with reviewer feedback, up to max_retries attempts.
    """

    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        validate_assignment=True,
    )

    ### Input Configuration ###
    user_goal: str = Field(
        ...,
        min_length=10,
        description="User's goal or bug description",
    )
    max_retries: int = Field(
        default=3,
        ge=0,
        le=10,
        description="Maximum review-reject retry cycles",
    )


    ### Planning Phase ###
    search_query: str | None = Field(
        default=None,
        description="Query generated by Planner for RAG search",
    )
    extracted_keywords: list[str] = Field(
        default_factory=list,
        description="Keywords extracted from user goal for hybrid search",
    )
    target_file_hint: str | None = Field(
        default=None,
        description="Specific file mentioned in user goal",
    )

    ### Retrieval Phase ###
    
    retrieved_context: list[CodeEntity] = Field(
        default_factory=list,
        description="Code entities retrieved from vector store",
    )
    search_metadata: dict = Field(
        default_factory=dict,
        description="Additional search metadata (scores, filters used, etc.)",
    )

    ### Coding Phase ###
    
    proposed_fix: str | None = Field(
        default=None,
        description="Generated fix from Coder agent",
    )
    confidence_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Coder's confidence in the fix (0-1)",
    )
    reasoning: str | None = Field(
        default=None,
        description="Coder's explanation of the fix",
    )

    # Review Phase
    review_feedback: str | None = Field(
        default=None,
        description="Reviewer's feedback if fix is rejected",
    )
    review_issues: list[str] = Field(
        default_factory=list,
        description="List of specific issues identified by reviewer",
    )
    is_approved: bool = Field(
        default=False,
        description="Whether the fix passed review",
    )

    ### State Tracking ###
    
    retry_count: int = Field(
        default=0,
        ge=0,
        description="Current retry attempt number",
    )
    status: Literal[
        "planning",
        "retrieving",
        "coding",
        "reviewing",
        "approved",
        "rejected",
        "failed",
    ] = Field(
        default="planning",
        description="Current state in the orchestration lifecycle",
    )
    history: list[dict] = Field(
        default_factory=list,
        description="History of state transitions for debugging",
    )

    @field_validator("user_goal")
    @classmethod
    def validate_user_goal(cls, v: str) -> str:
        """Ensure user goal is descriptive enough."""
        if len(v.strip()) < 10:
            raise ValueError("User goal must be at least 10 characters")
        return v.strip()

    def can_retry(self) -> bool:
        """Check if another retry is allowed.

        Returns:
            True if retry_count < max_retries
        """
        return self.retry_count < self.max_retries

    def get_context_summary(self) -> str:
        """Generate a summary of retrieved context for LLM prompts.

        Returns:
            Formatted string describing retrieved entities
        """
        if not self.retrieved_context:
            return "No context retrieved yet."

        lines = [f"Retrieved {len(self.retrieved_context)} code entities:"]
        for i, entity in enumerate(self.retrieved_context[:5], 1):  # Limit to top 5
            lines.append(f"  {i}. {entity.qualified_name} at {entity.location}")
            if entity.docstring:
                doc = entity.docstring[:80].replace("\n", " ")
                if len(entity.docstring) > 80:
                    doc += "..."
                lines.append(f"     Doc: {doc}")

        return "\n".join(lines)

    def get_fix_context(self) -> str:
        """Get formatted context for the fix.

        Combines retrieved code with proposed fix information.

        Returns:
            Formatted context string
        """
        parts = []

        if self.retrieved_context:
            parts.append("## Relevant Code\n")
            for entity in self.retrieved_context:
                parts.append(entity.to_chroma_document())
                parts.append("\n---\n")

        if self.proposed_fix:
            parts.append("## Proposed Fix\n")
            parts.append(self.proposed_fix)

        if self.review_feedback:
            parts.append("\n## Reviewer Feedback\n")
            parts.append(self.review_feedback)

        return "\n".join(parts)

    def log_transition(self, from_status: str, to_status: str, note: str = "") -> None:
        """Log a state transition for debugging and auditing."""
        from datetime import datetime

        self.history.append({
            "timestamp": datetime.now().isoformat(),
            "from": from_status,
            "to": to_status,
            "note": note,
            "retry_count": self.retry_count,
        })

    def to_retry_state(self) -> "AgentState":
        """Create a new state for retry attempt.

        Increments retry_count and resets coding-specific fields.

        Returns:
            New AgentState configured for retry
        """
        return AgentState(
            user_goal=self.user_goal,
            max_retries=self.max_retries,
            retry_count=self.retry_count + 1,
            status="coding",
            search_query=self.search_query,
            extracted_keywords=self.extracted_keywords,
            target_file_hint=self.target_file_hint,
            retrieved_context=self.retrieved_context,
            review_feedback=self.review_feedback,
            review_issues=self.review_issues,
            history=self.history + [{
                "transition": "retry",
                "retry_count": self.retry_count,
            }],
        )

    def model_dump_for_prompt(self) -> dict:
        """Dump state to dictionary suitable for LLM prompts.

        Excludes large context objects and internal fields.
        """
        return {
            "user_goal": self.user_goal,
            "search_query": self.search_query,
            "retry_count": self.retry_count,
            "max_retries": self.max_retries,
            "retrieved_count": len(self.retrieved_context),
            "proposed_fix": self.proposed_fix,
            "is_approved": self.is_approved,
            "review_feedback": self.review_feedback,
            "review_issues": self.review_issues,
        }
